# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VeloRouteClass
                                 A QGIS plugin
 some description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-15
        copyright            : (C) 2022 by yazmolod
        email                : yazmolod@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'yazmolod'
__date__ = '2022-02-15'
__copyright__ = '(C) 2022 by yazmolod'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VeloRouteClass class from file VeloRouteClass.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .velo_route_plugin import VeloRoutePlugin
    return VeloRoutePlugin()
