# -*- coding: utf-8 -*-

"""
/***************************************************************************
 VeloRouteClass
                                 A QGIS plugin
 some description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-15
        copyright            : (C) 2022 by yazmolod
        email                : yazmolod@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
__author__ = 'yazmolod'
__date__ = '2022-02-15'
__copyright__ = '(C) 2022 by yazmolod'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsMapLayer,
    QgsProcessing,
    QgsFeatureSink,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterDefinition,
    QgsProcessingParameterMapLayer,
    QgsProcessingParameterMultipleLayers,
    QgsProcessingParameterFeatureSink,
    QgsWkbTypes,
    QgsProcessingParameterNumber,
    QgsFields,
    QgsField,
    QgsCoordinateTransform,
    QgsProject,
    QgsFeature,
    )
from qgis.PyQt.QtCore import QVariant
from .framework import VeloGraph, iter_destination_paths, TARGET_CRS, DISTANCE_CALCULATOR


class DistanceCalculateAlgorithm(QgsProcessingAlgorithm):
    """
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    SIGN_INPUT = 'SIGN_INPUT'
    ROADS_INPUT = 'ROADS_INPUT'
    POIS_INPUT = 'POIS_INPUT'
    TOLERANCE = 'TOLERANCE'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(
            QgsProcessingParameterMapLayer(
                self.SIGN_INPUT,
                self.tr('Слой с носителями'),
                QgsProcessing.TypeVectorPoint
            )
        )        
        self.addParameter(
            QgsProcessingParameterMultipleLayers(
                self.POIS_INPUT,
                self.tr('Слои с объектами'),
                QgsProcessing.TypeVectorPoint
            )
        )        
        self.addParameter(
            QgsProcessingParameterMultipleLayers(
                self.ROADS_INPUT,
                self.tr('Слои с дорогами'),
                QgsProcessing.TypeVectorLine
            )
        )        
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Кратчайшие пути'),
                optional=True,
                type=QgsProcessing.TypeVectorLine
            )
        )
        advanced_params = []
        advanced_params.append(QgsProcessingParameterNumber(self.TOLERANCE,
                                                   self.tr('Topology tolerance'),
                                                   QgsProcessingParameterNumber.Double,
                                                   0.0, False, 0, 99999999.99))
        for p in advanced_params:
            p.setFlags(p.flags() | QgsProcessingParameterDefinition.FlagAdvanced)
            self.addParameter(p)



    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        sign_layer = self.parameterAsLayer(parameters, self.SIGN_INPUT, context)
        roads_layers = self.parameterAsLayerList(parameters, self.ROADS_INPUT, context)
        poi_layers = self.parameterAsLayerList(parameters, self.POIS_INPUT, context)
        tolerance = self.parameterAsDouble(parameters, self.TOLERANCE, context)
        
        graph = VeloGraph(roads_layers, [sign_layer]+poi_layers, tolerance, feedback)
        
        fields = QgsFields()
        fields.append(QgsField('id', QVariant.Int))
        fields.append(QgsField('from', QVariant.String))
        fields.append(QgsField('to', QVariant.String))
        fields.append(QgsField('length', QVariant.Double))
        sink, dest_id = self.parameterAsSink(parameters, self.OUTPUT,
                context, fields, QgsWkbTypes.LineString, TARGET_CRS)

        # Compute the number of steps to display within the progress bar and
        # get features from source
        feedback.setProgress(0)
        total = 100.0 / (sign_layer.featureCount()*4) if sign_layer.featureCount() else 0
        
        fid = 0
        sign_xform = QgsCoordinateTransform(sign_layer.sourceCrs(), TARGET_CRS, QgsProject.instance())
        for poi_layer, poi_feature, sign_feature in iter_destination_paths(sign_layer, poi_layers, feedback):
            if feedback.isCanceled():
                return {self.OUTPUT: dest_id}
            else:
                # project points to epsg 4326
                sign_geometry = sign_feature.geometry()
                sign_geometry.transform(sign_xform)
                poi_xform = QgsCoordinateTransform(poi_layer.sourceCrs(), TARGET_CRS, QgsProject.instance())
                poi_geometry = poi_feature.geometry()
                poi_geometry.transform(poi_xform)
                # calc shortest path
                vertex_ids = graph.shortest_path(sign_geometry.asPoint(), poi_geometry.asPoint())
                if not vertex_ids:
                    pass
                else:
                    path_line = graph.path_vector(vertex_ids)
                    feedback.pushInfo('[processAlgorithm] Shortest path calculated')
                    # make feature
                    feature = QgsFeature()
                    feature.setGeometry(path_line)
                    feature.setFields(fields)
                    feature['id'] = fid
                    feature['from'] = sign_feature['Name']
                    feature['to'] = poi_feature['NameRU']
                    feature['length'] = DISTANCE_CALCULATOR.measureLength(path_line)   
                    # Add a feature in the sink
                    sink.addFeature(feature, QgsFeatureSink.FastInsert)
                    # Update the progress bar
                    feedback.setProgress(int(fid * total))
                    fid += 1    
        return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'DistanceCalculate'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Group1'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return DistanceCalculateAlgorithm()
